package net.thunderbird.gradle.plugin.versioning.internal

import java.io.File
import java.io.StringWriter
import java.util.Properties
import kotlin.time.Clock
import kotlin.time.ExperimentalTime
import kotlin.time.Instant

class PropertiesWriter {

    @OptIn(ExperimentalTime::class)
    fun write(target: File, properties: Properties) {
        val writer = StringWriter()
        properties.store(writer, "Generated by VersioningPlugin")
        val lines = writer.toString().lineSequence().toMutableList()
        val now = Clock.System.now()
        val formattedDate = Instant.fromEpochSeconds(now.epochSeconds).toString()

        when {
            lines.size >= 2 && lines[0].startsWith("#") && lines[1].startsWith("#") -> {
                lines[0] = "# Generated by VersioningPlugin"
                lines[1] = "# $formattedDate"
            }
            lines.isNotEmpty() && lines[0].startsWith("#") -> {
                lines[0] = "# Generated by VersioningPlugin"
                lines.add(1, "# $formattedDate")
            }
            else -> {
                lines.add(0, "# Generated by VersioningPlugin")
                lines.add(1, "# $formattedDate")
            }
        }

        target.outputStream().use { output ->
            val finalContent = lines.joinToString(separator = System.lineSeparator())
            output.write(finalContent.toByteArray(Charsets.ISO_8859_1))
        }
    }

    private companion object {
        const val DATE_FORMAT = "yyyy-MM-dd HH:mm:ss"
    }
}
