package net.thunderbird.gradle.plugin.versioning.internal

import assertk.assertThat
import assertk.assertions.contains
import assertk.assertions.isEqualTo
import assertk.assertions.startsWith
import java.util.Properties
import kotlin.test.Test
import org.junit.Rule
import org.junit.rules.TemporaryFolder

class PropertiesWriterTest {

    @get:Rule
    val temporaryFolder = TemporaryFolder()

    @Test
    fun `write creates generated header and writes properties`() {
        // Arrange
        val file = temporaryFolder.newFile("version.properties")
        val properties = versionProperties()

        // Act
        PropertiesWriter().write(file, properties)

        // Assert
        val lines = file.readLines()
        assertThat(lines[0]).isEqualTo("# Generated by VersioningPlugin")
        assertThat(lines[1]).startsWith("# ")
        assertThat(file.readText()).contains("MAJOR=1", "MINOR=2", "PATCH=3")
    }

    @Test
    fun `write replaces existing generated header`() {
        // Arrange
        val file = temporaryFolder.newFile("version.properties")
        file.writeText(
            """
            # Old header
            # Old date
            MAJOR=0
            """.trimIndent(),
        )
        val properties = versionProperties()

        // Act
        PropertiesWriter().write(file, properties)

        // Assert
        val lines = file.readLines()
        assertThat(lines[0]).isEqualTo("# Generated by VersioningPlugin")
        assertThat(lines[1]).startsWith("# ")
        assertThat(file.readText()).contains("MAJOR=1", "MINOR=2", "PATCH=3")
    }

    private fun versionProperties(): Properties {
        return Properties().apply {
            setProperty("MAJOR", "1")
            setProperty("MINOR", "2")
            setProperty("PATCH", "3")
        }
    }
}
